// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// solve_jump_spline_fast
List solve_jump_spline_fast(NumericVector x_in, NumericVector y_in, double lambda, double M, int max_iter, double tol, double learning_rate, NumericVector gamma_init, double ebic_xi);
RcppExport SEXP _jumps_solve_jump_spline_fast(SEXP x_inSEXP, SEXP y_inSEXP, SEXP lambdaSEXP, SEXP MSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP learning_rateSEXP, SEXP gamma_initSEXP, SEXP ebic_xiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_in(x_inSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_in(y_inSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type learning_rate(learning_rateSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gamma_init(gamma_initSEXP);
    Rcpp::traits::input_parameter< double >::type ebic_xi(ebic_xiSEXP);
    rcpp_result_gen = Rcpp::wrap(solve_jump_spline_fast(x_in, y_in, lambda, M, max_iter, tol, learning_rate, gamma_init, ebic_xi));
    return rcpp_result_gen;
END_RCPP
}
// cssd_irregular_eigen
NumericVector cssd_irregular_eigen(NumericVector y_in, NumericVector x_in, double lambda, int max_iter, double rho);
RcppExport SEXP _jumps_cssd_irregular_eigen(SEXP y_inSEXP, SEXP x_inSEXP, SEXP lambdaSEXP, SEXP max_iterSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y_in(y_inSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_in(x_inSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(cssd_irregular_eigen(y_in, x_in, lambda, max_iter, rho));
    return rcpp_result_gen;
END_RCPP
}
// cssd_potts
List cssd_potts(NumericVector y_in, NumericVector x_in, double p, double gamma, NumericVector delta_in);
RcppExport SEXP _jumps_cssd_potts(SEXP y_inSEXP, SEXP x_inSEXP, SEXP pSEXP, SEXP gammaSEXP, SEXP delta_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y_in(y_inSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_in(x_inSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type delta_in(delta_inSEXP);
    rcpp_result_gen = Rcpp::wrap(cssd_potts(y_in, x_in, p, gamma, delta_in));
    return rcpp_result_gen;
END_RCPP
}
// cssd_potts_predict
NumericVector cssd_potts_predict(NumericVector y_in, NumericVector x_in, NumericVector f_hat_in, NumericVector disc_locs_in, NumericVector xq_in, double p, NumericVector delta_in);
RcppExport SEXP _jumps_cssd_potts_predict(SEXP y_inSEXP, SEXP x_inSEXP, SEXP f_hat_inSEXP, SEXP disc_locs_inSEXP, SEXP xq_inSEXP, SEXP pSEXP, SEXP delta_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y_in(y_inSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_in(x_inSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type f_hat_in(f_hat_inSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type disc_locs_in(disc_locs_inSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xq_in(xq_inSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type delta_in(delta_inSEXP);
    rcpp_result_gen = Rcpp::wrap(cssd_potts_predict(y_in, x_in, f_hat_in, disc_locs_in, xq_in, p, delta_in));
    return rcpp_result_gen;
END_RCPP
}
// da
void da(NumericVector k1, NumericVector k2, NumericMatrix X, NumericMatrix A1, NumericMatrix A2);
RcppExport SEXP _jumps_da(SEXP k1SEXP, SEXP k2SEXP, SEXP XSEXP, SEXP A1SEXP, SEXP A2SEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type k1(k1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type k2(k2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type A1(A1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type A2(A2SEXP);
    da(k1, k2, X, A1, A2);
    return R_NilValue;
END_RCPP
}
// llt
double llt(NumericVector y, NumericVector var_eps, NumericVector var_eta, NumericVector var_zeta, NumericVector cov_eta_zeta, NumericVector a1, NumericVector a2, NumericVector p11, NumericVector p12, NumericVector p22, NumericVector k1, NumericVector k2, NumericVector i, NumericVector f, NumericVector r1, NumericVector r2, NumericVector n11, NumericVector n12, NumericVector n22, NumericVector e, NumericVector d, Nullable<NumericVector> w_);
RcppExport SEXP _jumps_llt(SEXP ySEXP, SEXP var_epsSEXP, SEXP var_etaSEXP, SEXP var_zetaSEXP, SEXP cov_eta_zetaSEXP, SEXP a1SEXP, SEXP a2SEXP, SEXP p11SEXP, SEXP p12SEXP, SEXP p22SEXP, SEXP k1SEXP, SEXP k2SEXP, SEXP iSEXP, SEXP fSEXP, SEXP r1SEXP, SEXP r2SEXP, SEXP n11SEXP, SEXP n12SEXP, SEXP n22SEXP, SEXP eSEXP, SEXP dSEXP, SEXP w_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type var_eps(var_epsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type var_eta(var_etaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type var_zeta(var_zetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cov_eta_zeta(cov_eta_zetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a1(a1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a2(a2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p11(p11SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p12(p12SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p22(p22SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type k1(k1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type k2(k2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type i(iSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type f(fSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r1(r1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r2(r2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type n11(n11SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type n12(n12SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type n22(n22SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type e(eSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type w_(w_SEXP);
    rcpp_result_gen = Rcpp::wrap(llt(y, var_eps, var_eta, var_zeta, cov_eta_zeta, a1, a2, p11, p12, p22, k1, k2, i, f, r1, r2, n11, n12, n22, e, d, w_));
    return rcpp_result_gen;
END_RCPP
}
// llt_delta
double llt_delta(NumericVector y, NumericVector delta, NumericVector var_eps, NumericVector var_eta, NumericVector var_zeta, NumericVector cov_eta_zeta, NumericVector a1, NumericVector a2, NumericVector p11, NumericVector p12, NumericVector p22, NumericVector k1, NumericVector k2, NumericVector i, NumericVector f, NumericVector r1, NumericVector r2, NumericVector n11, NumericVector n12, NumericVector n22, NumericVector e, NumericVector d, Nullable<NumericVector> w_);
RcppExport SEXP _jumps_llt_delta(SEXP ySEXP, SEXP deltaSEXP, SEXP var_epsSEXP, SEXP var_etaSEXP, SEXP var_zetaSEXP, SEXP cov_eta_zetaSEXP, SEXP a1SEXP, SEXP a2SEXP, SEXP p11SEXP, SEXP p12SEXP, SEXP p22SEXP, SEXP k1SEXP, SEXP k2SEXP, SEXP iSEXP, SEXP fSEXP, SEXP r1SEXP, SEXP r2SEXP, SEXP n11SEXP, SEXP n12SEXP, SEXP n22SEXP, SEXP eSEXP, SEXP dSEXP, SEXP w_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type var_eps(var_epsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type var_eta(var_etaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type var_zeta(var_zetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cov_eta_zeta(cov_eta_zetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a1(a1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a2(a2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p11(p11SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p12(p12SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p22(p22SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type k1(k1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type k2(k2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type i(iSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type f(fSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r1(r1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r2(r2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type n11(n11SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type n12(n12SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type n22(n22SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type e(eSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type w_(w_SEXP);
    rcpp_result_gen = Rcpp::wrap(llt_delta(y, delta, var_eps, var_eta, var_zeta, cov_eta_zeta, a1, a2, p11, p12, p22, k1, k2, i, f, r1, r2, n11, n12, n22, e, d, w_));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_jumps_solve_jump_spline_fast", (DL_FUNC) &_jumps_solve_jump_spline_fast, 9},
    {"_jumps_cssd_irregular_eigen", (DL_FUNC) &_jumps_cssd_irregular_eigen, 5},
    {"_jumps_cssd_potts", (DL_FUNC) &_jumps_cssd_potts, 5},
    {"_jumps_cssd_potts_predict", (DL_FUNC) &_jumps_cssd_potts_predict, 7},
    {"_jumps_da", (DL_FUNC) &_jumps_da, 5},
    {"_jumps_llt", (DL_FUNC) &_jumps_llt, 22},
    {"_jumps_llt_delta", (DL_FUNC) &_jumps_llt_delta, 23},
    {NULL, NULL, 0}
};

RcppExport void R_init_jumps(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
