# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Alternating time-warping algorithm for smoothing splines with jumps
#'
#' @param x_in vector of observations for the x variable
#' @param y_in vector of observations for the y variable
#' @param lambda positive smoothing constant
#' @param M positive value for the maximum sum of the time extensions
#' @param max_iter positive integer with the maximum number of iterations
#' @param tol small positive number with tolerance for numerical convergence
#' @param learning_rate positive number: initial and fallback step size for the
#'   Barzilai-Borwein adaptive scheme (default 0.1).
#' @param gamma_init optional numeric vector of length n-1 with a warm-start
#'   value for gamma; ignored (zero initialisation used) when its length differs
#'   from n-1.
#' @param ebic_xi numeric scalar in [0,1]: strength of the extra Extended-BIC
#'   penalty 2*xi*k*log(n-1), where k is the number of active (nonzero) gamma_t.
#'   xi = 1 (default) is the Chen and Chen (2008) recommendation for genuinely
#'   sparse selection among many candidates; xi = 0 reduces ebic to plain bic.
#'
#' @returns A list with the following slots:
#' \describe{
#'   \item{f}{The smoothing spline with jumps computed at x.}
#'   \item{gamma}{The vector of added times (time jumps).}
#'   \item{df}{Derivative of f.}
#'   \item{edf}{Number of effective degrees of freedom.}
#'   \item{rss}{Residual sum of squares with residuals = y - f.}
#'   \item{gcv}{Generalized cross-validation.}
#'   \item{loglik}{Gaussian log-likelihood evaluated at the unbiased residual variance sigma^2 = rss/(n - edf).}
#'   \item{aic}{Akaike information criterion.}
#'   \item{aicc}{Akaike information criterion with bias correction.}
#'   \item{bic}{Bayesian information criterion.}
#'   \item{hq}{Hannan-Quinn information criterion.}
#'   \item{ebic}{Extended BIC, penalizing the search over n-1 candidate jump
#'     locations on top of the usual bic (see ebic_xi).}
#' }
solve_jump_spline_fast <- function(x_in, y_in, lambda, M, max_iter = 100L, tol = 1e-4, learning_rate = 0.1, gamma_init = numeric(0), ebic_xi = 1.0) {
    .Call(`_jumps_solve_jump_spline_fast`, x_in, y_in, lambda, M, max_iter, tol, learning_rate, gamma_init, ebic_xi)
}

#' ADMM solver for TV denoising with irregular sampling
#'
#' Solves min_u (1/2)||y - u||^2 + lambda*||Du||_1 where D is the weighted
#' first-difference matrix with (Du)_i = (u_{i+1} - u_i) / dx_i.
#' The system (I + rho*D'D) is factorized once and reused every iteration.
#'
#' @param y_in numeric vector of length n (no NAs).
#' @param x_in strictly increasing numeric vector of length n (the sample sites).
#' @param lambda positive regularization parameter.
#' @param max_iter maximum number of ADMM iterations (default 100).
#' @param rho positive augmented-Lagrangian step; affects convergence speed
#'   but not the solution (default 1.0).
#'
#' @return Numeric vector u of length n: the piecewise-constant minimizer.
cssd_irregular_eigen <- function(y_in, x_in, lambda, max_iter = 100L, rho = 1.0) {
    .Call(`_jumps_cssd_irregular_eigen`, y_in, x_in, lambda, max_iter, rho)
}

cssd_potts <- function(y_in, x_in, p, gamma, delta_in) {
    .Call(`_jumps_cssd_potts`, y_in, x_in, p, gamma, delta_in)
}

cssd_potts_predict <- function(y_in, x_in, f_hat_in, disc_locs_in, xq_in, p, delta_in) {
    .Call(`_jumps_cssd_potts_predict`, y_in, x_in, f_hat_in, disc_locs_in, xq_in, p, delta_in)
}

#' Internal function for computing scores w/r to regression coefficients
#' 
#' This function, not intended for end-users, implements the following
#' recursions needed in computing scores with respect to regression
#' coefficients:
#' \deqn{D a^{(1)}_{t+1} = D a^{(1)}_{t} + D a^{(2)}_{t} - k^{(1)}_t x_t -
#' k^{(1)}_t D a^{(1)}_{t}}
#' \deqn{D a^{(2)}_{t+1} = a^{(2)}_{t} - k^{(2)}_t x_t - k^{(2)}_t Da^{(1)}_{t}}
#' where \eqn{a^{(1)}_{t}}, \eqn{a^{(2)}_{t}} are the one-step-ahead Kalman filtered
#' state variables, and \eqn{k^{(1)}_{t}}, \eqn{k^{(2)}_{t}} the respective
#' Kalman gain elements. The symbol $D$ represent the partial derivative with
#' respect to the regression coefficients and $x_t$ is the vector of regressors.
#' All variables are passed by reference and, so, no output is needed.
#' 
#' @param k1 numeric vector of n elements with the Kalman gain sequence for
#' the first state variable;
#' @param k2 numeric vector of n elements with the Kalman gain sequence for
#' the second state variable;
#' @param X numeric matrix of dimension \eqn{n\times k} with the regressors;
#' @param A1 numeric matrix of dimension \eqn{n\times k} that, after calling
#' the function will contain the sequence of gradients \eqn{D a^{(1)}_t}; the
#' first row must be of zero values;
#' @param A2 numeric matrix of dimension \eqn{n\times k} that, after calling
#' the function will contain the sequence of gradients \eqn{D a^{(2)}_t}; the
#' first row must be of zero values;
#' @returns It does not return anything as it writes on the A1 and A2 matrices
#' passed as reference.
da <- function(k1, k2, X, A1, A2) {
    invisible(.Call(`_jumps_da`, k1, k2, X, A1, A2))
}

#' Kalman filtering and smoothing for local linear trend plus noise
#' 
#' It uses the power of C++, scalar computation and pointers
#' to run the Kalman filter, the smoother and compute the log-likelihood.
#' The R user has to supply many vectors that in most cases will be
#' overwritten by the llt() function since they are passed by reference.
#' All passed parameters must be numerical (floating point) vectors:
#' any other kind of variable may cause serious problems to the stability
#' of your system. Passing vectors of integers will make the computations fail.
#'  
#' @param y vector of n observations
#' @param var_eps vector of n variances for the observation noises
#' @param var_eta vector of n variances for the level disturbances
#' @param var_zeta vector of n variances for the slope disturbances
#' @param cov_eta_zeta vector of n covariances between level and slope disturbances
#' @param a1 vector of n+1 one-step-ahead prediction of the level; the first
#' element is the initial condition for the level at time t=1, the other elements
#' are arbitrary and will be overwritten
#' @param a2 vector of n+1 one-step-ahead prediction of the slope; the first
#' element is the initial condition for the slope at time t=1, the other elements
#' are arbitrary and will be overwritten
#' @param p11 vector of n+1 one-step-ahead prediction error variance of the level;
#' the first element is the initial condition for the level at time t=1, the other elements
#' are arbitrary and will be overwritten
#' @param p12 vector of n+1 one-step-ahead prediction covariances for level and slope;
#' the first element is the initial condition for the slope at time t=1, the other elements
#' are arbitrary and will be overwritten
#' @param p22 vector of n+1 one-step-ahead prediction error variance of the slope;
#' the first element is the initial condition for the level at time t=1, the other elements
#' are arbitrary and will be overwritten
#' @param k1 vector of the n Kalman gains for the level equation; values are
#' arbitrary and will be overwritten;
#' @param k2 vector of the n Kalman gains for the slope equation; values are
#' arbitrary and will be overwritten;
#' @param i vector of the n innovations; values are
#' arbitrary and will be overwritten;
#' @param f vector of the n innovatoin variances;values are
#' arbitrary and will be overwritten;
#' @param r1 vector of the n+1 smoothers (Th.5.4 in Pelagatti, 2015)
#' for the level equation; values are arbitrary and will be overwritten;
#' @param r2 vector of the n+1 smoothers (Th.5.4 in Pelagatti, 2015) for
#' the slope equation; values are arbitrary and will be overwritten;
#' @param n11 vector of the n+1 variance smoothers (Th.5.4 in Pelagatti, 2015) for the level
#' equation; values are arbitrary and will be overwritten;
#' @param n12 vector of the n+1 covariance smoothers (Th.5.4 in Pelagatti, 2015) for the level
#' and slope; values are arbitrary and will be overwritten;
#' @param n22 vector of the n+1 variance smoothers (Th.5.4 in Pelagatti, 2015) for the slope
#' equation; values are arbitrary and will be overwritten;
#' @param e vector of the n+1 observation error smoothers (Th.5.4 in Pelagatti, 2015);
#' values are arbitrary and will be overwritten;
#' @param d vector of the n+1 observation error variance smoothers (Th.5.4 in Pelagatti, 2015);
#' values are arbitrary and will be overwritten;
#' @param w_ NULL (default) or vector of n weights for the effect of observation y_t
#' on the estimation of the hp filter (with jumps) at time t;
#' values are arbitrary and will be overwritten;
#' @return The value of the Gaussian log-likelihood net of the -log(2*pi)*n/2 part
#' that can be added if needed.
llt <- function(y, var_eps, var_eta, var_zeta, cov_eta_zeta, a1, a2, p11, p12, p22, k1, k2, i, f, r1, r2, n11, n12, n22, e, d, w_ = NULL) {
    .Call(`_jumps_llt`, y, var_eps, var_eta, var_zeta, cov_eta_zeta, a1, a2, p11, p12, p22, k1, k2, i, f, r1, r2, n11, n12, n22, e, d, w_)
}

llt_delta <- function(y, delta, var_eps, var_eta, var_zeta, cov_eta_zeta, a1, a2, p11, p12, p22, k1, k2, i, f, r1, r2, n11, n12, n22, e, d, w_ = NULL) {
    .Call(`_jumps_llt_delta`, y, delta, var_eps, var_eta, var_zeta, cov_eta_zeta, a1, a2, p11, p12, p22, k1, k2, i, f, r1, r2, n11, n12, n22, e, d, w_)
}

